# codemagic.yaml
# Guía de compilación para IA Móvil en Codemagic

workflows:
  android-build:
    name: Build Android App (IA Móvil)
    instance_type: mac_mini_m1
    environment:
      vars: {}
    trigger:
      branch: main
    scripts:
      - name: Instalar Node.js y pnpm
        script: |
          npm install -g pnpm
          pnpm install

      - name: Compilar Frontend React (Web)
        script: |
          cd ai_mobile_frontend
          pnpm run build

      - name: Añadir Plataforma Android a Capacitor
        script: |
          cd ai_mobile_frontend
          npx cap add android

      - name: Sincronizar Proyecto Capacitor
        script: |
          cd ai_mobile_frontend
          npx cap sync android

      - name: Compilar Aplicación Android (APK)
        script: |
          cd ai_mobile_frontend/android
          ./gradlew assembleRelease

    artifacts:
      - ai_mobile_frontend/android/app/build/outputs/**/*.apk

  ios-build:
    name: Build iOS App (IA Móvil)
    instance_type: mac_mini_m1
    environment:
      vars: {}
    trigger:
      branch: main
    scripts:
      - name: Instalar Node.js y pnpm
        script: |
          npm install -g pnpm
          pnpm install

      - name: Compilar Frontend React (Web)
        script: |
          cd ai_mobile_frontend
          pnpm run build

      - name: Añadir Plataforma iOS a Capacitor
        script: |
          cd ai_mobile_frontend
          npx cap add ios

      - name: Sincronizar Proyecto Capacitor
        script: |
          cd ai_mobile_frontend
          npx cap sync ios

      - name: Configurar Certificados de Firma iOS
        script: |
          echo "Configuración de firma iOS gestionada por Codemagic"

      - name: Compilar Aplicación iOS (IPA)
        script: |
          cd ai_mobile_frontend/ios
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -destination 'generic/platform=iOS' -archivePath build/App.xcarchive archive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ipa

    artifacts:
      - ai_mobile_frontend/ios/build/ipa/**/*.ipa
